# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_c_counter_binary_0_0/mts_c_counter_binary_0_0.xci
# IP: The module: 'mts_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_c_counter_binary_0_0/mts_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_c_counter_binary_0_0/mts_c_counter_binary_0_0.xci
# IP: The module: 'mts_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_c_counter_binary_0_0/mts_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
