# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_IQ_product_0_0/mts_IQ_product_0_0.xci
# IP: The module: 'mts_IQ_product_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_IQ_product_0_0/iq_product_cmpy_v6_0_i0/iq_product_cmpy_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iq_product_cmpy_v6_0_i0 || ORIG_REF_NAME==iq_product_cmpy_v6_0_i0} -quiet] -quiet

# XDC: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_IQ_product_0_0/constrs/iq_product.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_IQ_product_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.srcs/sources_1/bd/mts/ip/mts_IQ_product_0_0/mts_IQ_product_0_0.xci
# IP: The module: 'mts_IQ_product_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_IQ_product_0_0/iq_product_cmpy_v6_0_i0/iq_product_cmpy_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iq_product_cmpy_v6_0_i0 || ORIG_REF_NAME==iq_product_cmpy_v6_0_i0} -quiet] -quiet

# XDC: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/ip/mts_IQ_product_0_0/constrs/iq_product.xdc
# XDC: The top module name and the constraint reference have the same name: 'mts_IQ_product_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
