# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts.xdc

# Block Designs: bd/mts/mts.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts || ORIG_REF_NAME==mts} -quiet] -quiet

# IP: bd/mts/ip/mts_BUFG_PL_CLK_0/mts_BUFG_PL_CLK_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_BUFG_PL_CLK_0 || ORIG_REF_NAME==mts_BUFG_PL_CLK_0} -quiet] -quiet

# IP: bd/mts/ip/mts_MTSclkwiz_0/mts_MTSclkwiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_MTSclkwiz_0 || ORIG_REF_NAME==mts_MTSclkwiz_0} -quiet] -quiet

# IP: bd/mts/ip/mts_PSreset_control_0/mts_PSreset_control_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_PSreset_control_0 || ORIG_REF_NAME==mts_PSreset_control_0} -quiet] -quiet

# IP: bd/mts/ip/mts_RFegressReset_0/mts_RFegressReset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_RFegressReset_0 || ORIG_REF_NAME==mts_RFegressReset_0} -quiet] -quiet

# IP: bd/mts/ip/mts_RFingressReset_0/mts_RFingressReset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_RFingressReset_0 || ORIG_REF_NAME==mts_RFingressReset_0} -quiet] -quiet

# IP: bd/mts/ip/mts_synchronizeSYSREF_0/mts_synchronizeSYSREF_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_synchronizeSYSREF_0 || ORIG_REF_NAME==mts_synchronizeSYSREF_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xbar_0/mts_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xbar_0 || ORIG_REF_NAME==mts_xbar_0} -quiet] -quiet

# IP: bd/mts/ip/mts_control_interconnect_0/mts_control_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_control_interconnect_0 || ORIG_REF_NAME==mts_control_interconnect_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_gpio_bram_adc_0/mts_axi_gpio_bram_adc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_gpio_bram_adc_0 || ORIG_REF_NAME==mts_axi_gpio_bram_adc_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_gpio_dac_0/mts_axi_gpio_dac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_gpio_dac_0 || ORIG_REF_NAME==mts_axi_gpio_dac_0} -quiet] -quiet

# IP: bd/mts/ip/mts_axi_gpio_fifoflush_0/mts_axi_gpio_fifoflush_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_axi_gpio_fifoflush_0 || ORIG_REF_NAME==mts_axi_gpio_fifoflush_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xpm_cdc_gen_0_0/mts_xpm_cdc_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xpm_cdc_gen_0_0 || ORIG_REF_NAME==mts_xpm_cdc_gen_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_system_management_wiz_0_0/mts_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_system_management_wiz_0_0 || ORIG_REF_NAME==mts_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_usp_rf_data_converter_1_0/mts_usp_rf_data_converter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_usp_rf_data_converter_1_0 || ORIG_REF_NAME==mts_usp_rf_data_converter_1_0} -quiet] -quiet

# IP: bd/mts/ip/mts_xlconcat_0_0/mts_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_xlconcat_0_0 || ORIG_REF_NAME==mts_xlconcat_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_zynq_ultra_ps_e_0_0/mts_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mts_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_IQ_product_0_0/mts_IQ_product_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_IQ_product_0_0 || ORIG_REF_NAME==mts_IQ_product_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_ila_0_0/mts_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_ila_0_0 || ORIG_REF_NAME==mts_ila_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_c_counter_binary_0_0/mts_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_c_counter_binary_0_0 || ORIG_REF_NAME==mts_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_blk_mem_gen_0_5/mts_blk_mem_gen_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_blk_mem_gen_0_5 || ORIG_REF_NAME==mts_blk_mem_gen_0_5} -quiet] -quiet

# IP: bd/mts/ip/mts_vio_0_0/mts_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_vio_0_0 || ORIG_REF_NAME==mts_vio_0_0} -quiet] -quiet

# IP: bd/mts/ip/mts_auto_pc_0/mts_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mts_auto_pc_0 || ORIG_REF_NAME==mts_auto_pc_0} -quiet] -quiet

# XDC: c:/Work/FPGA/RFSoC-MTS/boards/RFSoC4x2/build_mts/mts/mts.gen/sources_1/bd/mts/mts_ooc.xdc
